const products = [
  {
    id: 1,
    name: "Ocean Breeze",
    category: "Fresh",
    price: 1200,
    image: "/images/ocean-breeze.jpg",
  },
  {
    id: 2,
    name: "Rose Delight",
    category: "Floral",
    price: 950,
    image: "/images/rose-delight.jpg",
  },
  {
    id: 3,
    name: "Spicy Oud",
    category: "Woody",
    price: 1800,
    image: "/images/spicy-oud.jpg",
  },
  {
    id: 4,
    name: "Citrus Spark",
    category: "Citrus",
    price: 1100,
    image: "/images/citrus-spark.jpg",
  },
  {
    id: 5,
    name: "Lavender Fields",
    category: "Floral",
    price: 1300,
    image: "/images/lavender-fields.jpg",
  },
  {
    id: 6,
    name: "Dark Amber",
    category: "Woody",
    price: 1700,
    image: "/images/dark-amber.jpg",
  },
  {
    id: 7,
    name: "Vanilla Dream",
    category: "Sweet",
    price: 1050,
    image: "/images/vanilla-dream.jpg",
  },
  {
    id: 8,
    name: "Green Mist",
    category: "Fresh",
    price: 980,
    image: "/images/green-mist.jpg",
  },
  {
    id: 9,
    name: "Night Bloom",
    category: "Floral",
    price: 1250,
    image: "/images/night-bloom.jpg",
  },
  {
    id: 10,
    name: "Woody Trail",
    category: "Woody",
    price: 1900,
    image: "/images/woody-trail.jpg",
  },
  {
    id: 11,
    name: "Citrus Chill",
    category: "Citrus",
    price: 950,
    image: "/images/citrus-chill.jpg",
  },
  {
    id: 12,
    name: "Spice Affair",
    category: "Oriental",
    price: 1450,
    image: "/images/spice-affair.jpg",
  },
  {
    id: 13,
    name: "Fresh Meadow",
    category: "Fresh",
    price: 990,
    image: "/images/fresh-meadow.jpg",
  },
  {
    id: 14,
    name: "Jasmine Kiss",
    category: "Floral",
    price: 1190,
    image: "/images/jasmine-kiss.jpg",
  },
  {
    id: 15,
    name: "Oud Royale",
    category: "Woody",
    price: 2100,
    image: "/images/oud-royale.jpg",
  },
  {
    id: 16,
    name: "Sweet Whisper",
    category: "Sweet",
    price: 970,
    image: "/images/sweet-whisper.jpg",
  },
  {
    id: 17,
    name: "Tropical Zest",
    category: "Citrus",
    price: 1120,
    image: "/images/tropical-zest.jpg",
  },
  {
    id: 18,
    name: "Amber Spice",
    category: "Oriental",
    price: 1550,
    image: "/images/amber-spice.jpg",
  },
];

export default products;
